apiVersion: v1alpha
kind: puppeteer
sauce:
  region: us-west-1
  concurrency: 1
  # meta data to the test
  metadata:
    name: Testing Puppeteer Support
    tags:
      - e2e
      - release team
      - other tag
    build: "Build #$BUILD_ID in $BUILD_ENV"
# Every file defined in this list will be bundled into a zip and
# uploaded to Sauce Labs.
rootDir: ./
puppeteer:
  version: 3.0.4
suites:
  - name: "chrome"
    testMatch: ["**/*.test.js"]
    browser: "chrome"